const tintColor = '#2f95dc';

export default {
  blue: '#2795F4',
  greenLight: 'rgba(0, 213, 213, 0.3)',
  blueLight: 'rgba(39, 149, 244, 0.3)',
  blueBottom: '#E4ECF3',
  green: '#00CE8C',
  black: '#292929',
  grey: '#707070',
  buttongrey: '#CCCCCC',
  borderGrey: '#EAEAEA',
  red: '#FF5555',
  tintColor,
  default: '#F9FAFE',
  white: '#ffffff',
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  STATUSBAR_COLOR: '#560027',
  HEADER_COLOR: '#880e4f',
  CARD_BG_COLOR: '#ffffff',
  HEADER_TEXT_COLOR: '#ffffff',
  HEADER_BACK_ICON_COLOR: '#ffffff',
  BLACK: '#000000',
};
